### ISSUE TITLE
regarding saving the file

### ISSUE THREAD

**Issue by aiswariyamilan** [AshwinRJ/Federated-Learning-PyTorch#20]
While executing federated learning code and MLP code i am getting this error
raceback (most recent call last):
  File "src/federated_main.py", line 129, in <module>
    with open(file_name, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../save/objects/cifar_cnn_5_C[0.1]_iid[1]_E[10]_B[10].pkl'
170500096it [09:57, 285128.32it/s]
whether i have to create some files

**Comment by aiswariyamilan** [comment]
please help me regarding this

**Comment by SamiurRahman1** [comment]
hello! did you figure out where the problem was? i am facing the same issue.
